# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/Gimbal.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/Waypoint.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/WaypointList.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/MobileData.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/MissionWaypointAction.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/MissionWaypoint.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/MissionWaypointTask.msg;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg/MissionHotpointTask.msg"
services_str = "/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/Activation.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/CameraAction.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/DroneTaskControl.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/SDKControlAuthority.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/SetLocalPosRef.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MFIOConfig.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MFIOSetValue.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/DroneArmControl.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionStatus.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionWpAction.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpAction.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionWpUpload.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionWpSetSpeed.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionWpGetSpeed.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionWpGetInfo.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpUpload.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpGetInfo.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpUpdateYawRate.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpUpdateRadius.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/MissionHpResetYaw.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/SendMobileData.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/SetHardSync.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/QueryDroneVersion.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/Stereo240pSubscription.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/StereoVGASubscription.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/StereoDepthSubscription.srv;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/srv/SetupCameraStream.srv"
pkg_name = "dji_sdk"
dependencies_str = "geometry_msgs;nav_msgs;std_msgs;sensor_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "dji_sdk;/home/ubuntu/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg;geometry_msgs;/opt/ros/indigo/share/geometry_msgs/cmake/../msg;nav_msgs;/opt/ros/indigo/share/nav_msgs/cmake/../msg;std_msgs;/opt/ros/indigo/share/std_msgs/cmake/../msg;sensor_msgs;/opt/ros/indigo/share/sensor_msgs/cmake/../msg;actionlib_msgs;/opt/ros/indigo/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = 'TRUE' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/indigo/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
